[package]
name = "miniaudio-sys"
version = "0.1.0"
authors = ["Adolph C. <adolphc@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["log-level-error"]

no-wasapi = []
no-dsound = []
no-winmm = []
no-alsa = []
no-pulseaudio = []
no-jack = []
no-coreaudio = []
no-sndio = []
no-audio4 = []
no-oss = []
no-aaudio = []
no-opensl = []
no-webaudio = []
no-null = []
no-decoding = []
no-device-io = []
no-stdio = []
no-sse2 = []
no-avx2 = []
no-avx512 = []
no-neon = []

log-level-verbose = []
log-level-info = []
log-level-warning = []
log-level-error = []

debug-output = []

[dependencies]

[build-dependencies]
cc = "1.0"
