name: Bindgen

on:
    push:
        branches:
            - master
        paths:
            - '.gitmodules'
            - 'miniaudio-sys/miniaudio'
            - 'miniaudio-sys/miniaudio'
            - 'generate-bindings.rs'
            - '.github/workflows/bindgen.yml'
            - 'miniaudio-sys/build.rs'

jobs:
    bindgen:
        name: ${{ matrix.rust_channel }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
        - uses: actions/checkout@v2
        - name: Checkout Submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule sync --recursive
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              profile: default
              override: true
              components: rustfmt
        - name: Install LLVM (Windows)
          run: choco install llvm
          if: matrix.os == 'windows-latest'
        - name: Install Bindgen
          run: cargo install bindgen
        - name: Generate Bindings
          run: |
            rustc -o generate-bindings generate-bindings.rs
            ./generate-bindings
          if: matrix.os != 'windows-latest'
        - name: Generate Bindings (Windows)
          run: |
            rustc -o generate-bindings.exe generate-bindings.rs
            .\generate-bindings.exe
          if: matrix.os == 'windows-latest'

        # Run Tests:
        - name: Test
          run: cargo test -vv --manifest-path=miniaudio-sys/Cargo.toml --no-default-features --features ma-log-level-error

        - name: Setup Git
          run: |
            git config --global user.email expixel+miniaudio-rs+bindgen@github.com
            git config --global user.name miniaudio-rs-bindgen
        - name: Commit And Push Bindings
          run: |
            git add miniaudio-sys/bindings
            git diff --quiet && git diff --staged --quiet || git commit -m "Updated bindings for ${{ matrix.os }}"
            git pull --rebase origin master
            git push origin master
